name: Jix Settings
description: 'Jix global settings and configuration module.'
package: Jix Custom Modules

type: module
core_version_requirement: ^9
version: '9.x-1.0'

dependencies:
  - twig_tweak:twig_tweak
  - phpseclib
