<?php
/**
 * @file
 * A description of what your module does.
 */

use Drupal\Component\Utility\Random;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\field\Entity\FieldConfig;
use Drupal\file\Entity\File;
use Drupal\jix_settings\Form\WebsiteSettingsForm;
use Drupal\node\NodeInterface;
use Drupal\smart_ip\SmartIpLocationInterface;
use Drupal\webform\WebformSubmissionInterface;


/**
 * Implements hook_theme().
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function jix_interface_theme($existing, $type, $theme, $path): array
{
  return [
    'jix_upload_cv' => [
      'variables' => [
        'label' => ''
      ]
    ],
    'jix_job_summary' => [
      'variables' => [
        'job' => [],
        'viewsCount' => 0,
        'lang' => '',
        'timezone' => ''
      ]
    ],
    'jix_job_employer' => [
      'variables' => [
        'employer' => [],
        'logged_in' => false,
        'pageNodeBundle' => ''
      ]
    ],
    'jix_posting_plans_page' => [
      'variables' => [
        'plans' => [],
        'header_text' => '',
        'footer_text' => ''
      ]
    ],
    'jix_copyright' => [
      'variables' => [
        'year' => date('Y'),
        'terms' => t('Terms of Use'),
        'privacy' => t('Privacy Policy'),
        'owner' => Drupal::config('system.site')->get('owner'),
        'admin' => t('Site administration')
      ]
    ],
    'jix_address' => [
      'variables' => [
        'title' => t('Get in touch'),
        'owner' => Drupal::config(WebsiteSettingsForm::SETTINGS)->get('site_owner'),
        'address1' => Drupal::config(WebsiteSettingsForm::SETTINGS)->get('site_address_line_1'),
        'address2' => Drupal::config(WebsiteSettingsForm::SETTINGS)->get('site_address_line_2'),
        'phone' => Drupal::config(WebsiteSettingsForm::SETTINGS)->get('site_phone'),
      ]
    ],
    'jix_services' => [
      'variables' => [
        'title' => t('Our services'),
        'services' => null
      ]
    ],
    'jix_jobs_sites' => [
      'variables' => [
        'title' => t('Jobs elsewhere'),
        'sites' => []
      ]
    ],
    'jix_realtime_stats' => [
      'variables' => [
        'title' => t('Realtime figures'),
        'jobs_count' => 0,
        'employers_count' => 0,
        'candidates_count' => 0
      ]
    ],
    'jix_social_media_buttons' => [
      'variables' => [
        'facebook' => '',
        'twitter' => '',
        'instagram' => '',
        'youtube' => '',
        'linkedin' => ''
      ]
    ],
    'jix_similar_jobs' => [
      'variables' => [
        'jobs' => []
      ]
    ],
    'error_404' => [
      'variables' => []
    ]
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 * @param EntityInterface $entity
 */
function jix_interface_node_presave(EntityInterface $entity): void
{
  if ($entity instanceof NodeInterface and $entity->bundle() == 'job') {
    $consumeCredit = false;
    if ($entity->isNew()) {
      /** Set creator location **/
      $locationObj = Drupal::service('smart_ip.smart_ip_location');
      if ($locationObj instanceof SmartIpLocationInterface) {
        $locationData = $locationObj->getData(false);
        $location = $locationData['city'] . ', ' . $locationData['country'] . ' (' . $locationData['countryCode'] . ')';
        $entity->set('field_job_creator_location', $location);
      }
      $consumeCredit = $entity->isPublished();
    } else {
      $originalJob = $entity->original;
      if ($originalJob instanceof NodeInterface) {
        $consumeCredit = !$originalJob->isPublished() and $entity->isPublished();
      }
    }

    /** Compute credits **/
    if ($consumeCredit) {
      $employer = $entity->get('field_job_employer')->entity;
      Drupal::service('jix_interface.employer_credits_service')->consumeCredit($employer);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function jix_interface_webform_submission_presave(EntityInterface $entity): void
{
  if ($entity->bundle() === 'default_job_application_form' && $entity instanceof WebformSubmissionInterface) {
    if ($entity->isNew()) {
      /**
       * Rename cv and other files
       */
      $data = $entity->getData();
      $cvFileId = $data['job_application_cv_resume_file'];
      if (!empty($cvFileId)) {
        $cvFile = File::load(intval($cvFileId));
        $hash = md5((new Random())->string(20));
        $today = date('YmdHis', (new DrupalDateTime())->getTimestamp());
        $extension = pathinfo($cvFile->getFileUri())['extension'];
        $cvFile->setFilename($hash . '_' . $today . '_cv_file.' . $extension);
      } else {
        Drupal::logger('Jix debugger')->debug('Submission ' . $entity->id() . ' has no CV file');
      }

      $otherFileIds = $data['job_application_other_files'];
      if (!empty($otherFileIds)) {
        foreach ($otherFileIds as $otherFileId) {
          $otherFile = File::load(intval($otherFileId));
          $hash = md5((new Random())->string(20));
          $today = date('YmdHis', (new DrupalDateTime())->getTimestamp());
          $extension = pathinfo($otherFile->getFileUri())['extension'];
          $otherFile->setFilename($hash . '_' . $today . '_additional_file.' . $extension);
        }
      }

      /**
       * Lookup user location
       */
      $locationObj = Drupal::service('smart_ip.smart_ip_location');
      if ($locationObj instanceof SmartIpLocationInterface) {
        $locationData = $locationObj->getData(false);
        $location = $locationData['city'] . ', ' . $locationData['country'] . ' (' . $locationData['countryCode'] . ')'; //[random:hash:md5]_[current-date:concatenated_date_time]_cv_file
        $entity->setElementData('job_application_candidate_location', $location);
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_create().
 * @param EntityInterface $entity
 */
function jix_interface_node_create(EntityInterface $entity): void
{
  if ($entity instanceof NodeInterface and $entity->bundle() == 'job') {
    $postingPlan = Drupal::request()->get('posting_plan');
    if (isset($postingPlan) && strlen($postingPlan) > 0) {
      $entity->set('field_job_posting_plan', $postingPlan);
    }
  }
}

/**
 * Implements hook_field_widget_form_alter().
 * @param $element
 * @param FormStateInterface $form_state
 * @param $context
 */
function jix_interface_field_widget_form_alter(&$element, FormStateInterface $form_state, $context): void
{
  $field_definition = $context['items']->getFieldDefinition();

  // Base fields are not configurable.
  if (!$field_definition instanceof FieldConfig) {
    return;
  }
  if ($field_definition->getName() === 'field_job_full_description'
    or $field_definition->getName() === 'field_employer_summary') {
    // Set only full_html as allowed format.
    $element['#allowed_formats'] = ['full_html'];
    // Add after build to remove the help wrapper and text.
    $element['#after_build'][] = 'jix_interface_after_build';
  }

  if ($field_definition->getName() === 'field_testimonial_message') {
    $element['#allowed_formats'] = ['basic_html'];
    $element['#after_build'][] = 'jix_interface_after_build';
  }
}

function jix_interface_after_build(array $element, FormStateInterface $form_state): array
{
  unset($element['format']['help']);
  unset($element['format']['guidelines']);
  unset($element['format']['#type']);
  unset($element['format']['#theme_wrappers']);
  return $element;
}

/**
 * Implements hook_views_data_alter().
 */
function jix_interface_views_data_alter(array &$data): void
{
  $data['node']['job_submissions_count_views_field'] = [
    'title' => t('Job submissions count'),
    'field' => [
      'title' => t('Job submissions count'),
      'help' => t('Number of submissions a job has.'),
      'id' => 'job_submissions_count_views_field'
    ],
  ];
}
