<?php
/**
 * @file
 * A description of what your module does.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\jix_interface\Form\WebsiteSettingsForm;
use Drupal\node\NodeInterface;


/**
 * Implements hook_theme().
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function jix_interface_theme($existing, $type, $theme, $path): array
{
  return [
    'jix_upload_cv' => [
      'variables' => [
        'label' => ''
      ]
    ],
    'jix_job_summary' => [
      'variables' => [
        'job' => [],
        'viewsCount' => 0
      ]
    ],
    'jix_job_employer' => [
      'variables' => [
        'employer' => [],
        'pageNodeBundle' => ''
      ]
    ],
    'jix_posting_plans_page' => [
      'variables' => [
        'plans' => [],
        'header_text' => '',
        'footer_text' => ''
      ]
    ],
    'jix_copyright' => [
      'variables' => [
        'year' => date('Y'),
        'terms' => t('Terms of Use'),
        'privacy' => t('Privacy Policy'),
        'owner' => Drupal::config('system.site')->get('owner'),
        'admin' => t('Site administration')
      ]
    ],
    'jix_address' => [
      'variables' => [
        'title' => t('Get in touch'),
        'owner' => Drupal::config(WebsiteSettingsForm::SETTINGS)->get('site_owner'),
        'address1' => Drupal::config(WebsiteSettingsForm::SETTINGS)->get('site_address_line_1'),
        'address2' => Drupal::config(WebsiteSettingsForm::SETTINGS)->get('site_address_line_2'),
        'phone' => Drupal::config(WebsiteSettingsForm::SETTINGS)->get('site_phone'),
      ]
    ],
    'jix_services' => [
      'variables' => [
        'title' => t('Our services'),
        'services' => null
      ]
    ],
    'jix_jobs_sites' => [
      'variables' => [
        'title' => t('Jobs elsewhere'),
        'sites' => []
      ]
    ],
    'jix_realtime_stats' => [
      'variables' => [
        'title' => t('Realtime figures'),
        'jobs_count' => 0,
        'employers_count' => 0,
        'candidates_count' => 0
      ]
    ]
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 * @param EntityInterface $entity
 */
function jix_interface_node_presave(EntityInterface $entity)
{
  if ($entity instanceof NodeInterface and $entity->bundle() == 'job') {
    if ($entity->isNew()) {
      $locationObj = Drupal::service('smart_ip.smart_ip_location');
      $location = $locationObj->get('city') . ', ' . $locationObj->get('country') . '(' . $locationObj->get('countryCode') . ')';
      $entity->set('field_job_creator_location', $location);
    }
  }
}
